### ISSUE TITLE
Can not run on Ubuntu Minecraft server

### ISSUE THREAD

**Issue by Michael-BJ-CN** [Steve-Tech/DynamicDNS-Spigot#1]
Hi Steve, 

I build a Minecraft server on Raspberry Pi 4 with Ubuntu 64-bit for my kids. I copied the JAR file into **plugins** folder and modified the config.yml file in the DuckDNS folder. I checked the Minecraft server status and it is running, also the DynamicDNS plugins. When logging into DuckDNS website, the IP address is not changed, even I used /updateip on the Minecraft server.

After that I build another Minecraft server on Windows 10 and did the same thing, it's working!

Did I miss something on Raspberry Pi 4?

Thanks!

**Comment by Steve-Tech** [comment]
Hi Michael,

Are there any errors in the log or does it just seem to update successfully but actually not?
Also what version are you running?

Thanks,
Steve

**Comment by Michael-BJ-CN** [comment]
Hi Steve,

I have made some tests and found out that I cannot access DuckDNS at home,
my ISP has blocked it. So the DynamicDNS plugin cannot work. It's so sad!
You made a great job, and the Plugin is so simple to use.

Sorry for the late reply!

Michael

Stephen H ***@***.***> 于2021年5月20日周四 下午3:22写道：
